### ISSUE TITLE
Waypoints/Markers and explored tiles not retained after server leave-join

### ISSUE THREAD

**Issue by OreoTheAvali** [sleepingdragoninn/antique-atlas#17]
Mod Version: 1.1.2 [Beta] Quilt

_Issue:_ Markers placed on the map and explored tiles are not retained after logging out of server.
_Expected:_ Markers and tiles to be retained between sessions.

_Reproduction:_
1. Place a pin, walk away from location (preferably adding more tiles to the atlas)
2. Log out
3. Log back in, observe markers missing and map tiles being reset to those around the spawn location
Before logging out: ![javaw_ckgzJrdUfa](https://github.com/sisby-folk/antique-atlas/assets/20571140/316e70c3-50bf-4207-88ce-27b837c3648d)
After logged back in: ![javaw_TYOAKVcW02](https://github.com/sisby-folk/antique-atlas/assets/20571140/1d42cd1f-ec75-4147-af0a-f131aa1e9f0a)

Server log: https://mclo.gs/Z1Fb9x7
Client log: https://mclo.gs/TyAs73N

**Comment by sleepingdragoninn** [comment]
This is a duplicate of #13 but your log and screenshots are way better so you win the issue battle and we're closing that one instead lmao

**Comment by crabinpenguin** [comment]
lmao thanks, any luck theres been progress in figuring this out?

**Comment by OreoTheAvali** [comment]
I figured I'd write my own because corbin's was _maybe_ caused by a crash. So there was a chance mine was different™ and I thought I'd toss my hat into the ring.

**Comment by crabinpenguin** [comment]
my log came from an instance that my game closed due to a crash, but the issue has been happening during other occurrences of just exiting the game and entering again too

**Comment by OreoTheAvali** [comment]
My issue just started on this new version. Before it would save the markers but not the tiles. I assumed it not saving the tiles was a design choice or something that had to do with the lack of an item like the older antique atlas. But reading your issue, Corbin, made it seem like maybe it wasn't supposed to be not saving the tiles. So I figured I'd mention them.

**Comment by sleepingdragoninn** [comment]
We're testing this at the moment - How it appears to work is that data is sent correctly only the first time the player connects to the server for that server run - on subsequent joins, it consistently fails.

**Comment by OreoTheAvali** [comment]
I really hope y'all find a fix. I love this mod to death and while I can't code I can offer bug reports where I can.

**Comment by crabinpenguin** [comment]
i also hope a fix is found, antique atlas is honestly my favorite map-style mod, due to how well it blends in with the vanilla theme. I dont want to have a little minimap in the corner all the time, and im not a huge fan of actual vanilla maps

**Comment by sleepingdragoninn** [comment]
Oh yeah no don't worry we'll sort it out just fine, we're fairly familiar with the innards of the mod at this point.

From what we've gathered in a few minutes it seems like the server is saving and sending markers just fine, but the client isn't accepting them properly on the other side.

**Comment by sleepingdragoninn** [comment]
Yeah bug isolated:

![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/154bc785-f6d9-4729-84ee-1b2faff4c405)

this event where the client clears out its map data is running _after_ receiving map data from the server. Will fix and release 1.1.3.

**Comment by sleepingdragoninn** [comment]
Should be fixed in 1.1.3, just moved the data clearing to INIT instead of JOIN so it happens earlier.

**Comment by OreoTheAvali** [comment]
So just to clarify; Are the explored tiles not being saved between server sessions a design choice or is that a residual bug? I'm fine with either or I'm just curious.

I only ask because the description for the mod on Modrinth says:

> Exploration progress is not lost on death, and the atlas doesn't occupy a physical slot.

**Comment by sleepingdragoninn** [comment]
Exploration progress and markers should definitely be persistent for players, otherwise its a bug - the only thing we removed from the save is where the map was open to last (as in, literally where the screen was previously panned to)

If that still occurs, let me know and I'll reopen this or start a new issue if it occurs under different conditions.

**Comment by OreoTheAvali** [comment]
Yeah, my explored tiles are still disappearing. It still happens under the same conditions of leaving and joining a server.
Let me get a clean server running with only this mod to see if it's actually atlas's fault.

**Comment by sleepingdragoninn** [comment]
yeah, can reproduce, reopening

**Comment by OreoTheAvali** [comment]
Would you still like my logs are y'all good with supplying your own?

**Comment by sleepingdragoninn** [comment]
should be good! seems like a client problem again.

**Comment by sleepingdragoninn** [comment]
Should be fixed in 1.1.4 - we were trying to update the map tiles on the networking thread, which means the client world didn't exist yet and it simply exited early.

**Comment by OreoTheAvali** [comment]
I can confirm the tiles loaded upon joining the server this time. glad that's been sorted out finally.
